apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-frgl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-frgl@sha256:e45a8ba570e5a833fc3af04dccf5af56abbb9a8c14467773d051b2b5ecfd36c1
        name: my-nodejs
        resources: {}
status: {}
